// Seed data for Seyon Hunga EMBA Admissions 2027 tracker.
// Written once on first launch. Never overwritten on redeploy.
// Classic script (no ES modules) so the app also works opened from file://.

const SEED_VERSION = 1;

const t = (id, label, due = null) => ({ id, label, due, done: false });

// Per-school task template. Cloned for each school.
const schoolTasks = (deadline) => [
  t('research', 'Research programme and confirm dates', null),
  t('waiver', 'Secure GMAT/GRE waiver', null),
  t('para', 'Write school-specific paragraph', null),
  t('essay', 'Adapt personal statement to essay prompt', null),
  t('recs', 'Brief recommenders', null),
  t('scholarship', 'Submit scholarship application', null),
  t('submit', 'Submit application', deadline),
];

const SCHOOLS = [
  {
    id: 'cambridge-emba',
    name: 'Cambridge Judge EMBA',
    geo: 'Europe',
    priority: 'HIGH',
    waiver: 'Amber',
    waiverNote: 'Post-interview waiver. 2:1 degree satisfies academic requirement.',
    tuitionLocal: 98100, ccy: 'GBP', tuitionUsd: 124587,
    totalUsd: 133668,
    duration: '20 months',
    start: 'Sep 2027',
    deadline: '2026-11-15',
    deadlineNote: 'R1 estimate for Sep 2027 start — verify with Judge',
    estimated: true,
    flag: 'This deadline is an estimate for the Sep 2027 intake, not a confirmed date. Contact Cambridge Judge admissions to confirm round dates.',
    scholarship: 'Up to 50% of fees. Apply simultaneously with programme application.',
    scholarshipTiming: 'Simultaneously with application',
  },
  {
    id: 'insead-gemba',
    name: 'INSEAD GEMBA',
    geo: 'Europe',
    priority: 'HIGH',
    waiver: 'Green',
    waiverNote: 'Own Executive Test — no GMAT/GRE needed.',
    tuitionLocal: 142150, ccy: 'EUR', tuitionUsd: 153522,
    totalUsd: 177552,
    duration: '14–17 months',
    start: 'Nov 2027',
    deadline: '2027-02-15',
    deadlineNote: 'R1 estimate for Nov 2027 intake — confirm with INSEAD',
    estimated: true,
    scholarship: '~60% of class receive awards. Average ~10% of tuition. Diversity Scholarship and Financial Fellowship.',
    scholarshipTiming: 'Post-admission (up to 2 awards)',
  },
  {
    id: 'imd-emba',
    name: 'IMD EMBA',
    geo: 'Europe',
    priority: 'HIGH',
    waiver: 'Amber',
    waiverNote: 'Waiver letter required. Strong CFA and seniority case.',
    tuitionLocal: 125000, ccy: 'CHF', tuitionUsd: 140000,
    totalUsd: 170000,
    duration: '15–18 months',
    start: 'Rolling',
    deadline: '2026-09-15',
    deadlineNote: 'Round 5 — confirm it feeds a 2027 start',
    scholarship: 'Merit-based scholarships. Contact IMD financial aid.',
    scholarshipTiming: 'Contact IMD financial aid',
  },
  {
    id: 'oxford-said',
    name: 'Oxford Saïd EMBA',
    geo: 'Europe',
    priority: 'HIGH',
    waiver: 'Amber',
    waiverNote: 'Post-interview waiver. Apply before interview stage.',
    tuitionLocal: 132420, ccy: 'GBP', tuitionUsd: 168173,
    totalUsd: 183268,
    duration: '22–24 months',
    start: 'Jan 2027 / Sep 2027',
    deadline: '2026-09-30',
    deadlineNote: 'Confirm R1 date with admissions',
    estimated: true,
    scholarship: "Director's Awards: up to 30% of fees. Strong fit given African finance background.",
    scholarshipTiming: 'At point of programme application',
  },
  {
    id: 'lbs-emba',
    name: 'LBS EMBA',
    geo: 'Europe',
    priority: 'HIGH',
    waiver: 'Amber',
    waiverNote: 'Waiver letter required. Strong CFA and seniority case.',
    tuitionLocal: 134950, ccy: 'GBP', tuitionUsd: 171387,
    totalUsd: 181533,
    duration: '17–22 months',
    start: 'Sep 2027',
    deadline: '2026-09-30',
    deadlineNote: 'Confirm R1 date with admissions',
    estimated: true,
    scholarship: 'Merit scholarships for self-sponsored applicants.',
    scholarshipTiming: 'Post-offer',
  },
  {
    id: 'trium',
    name: 'TRIUM Global EMBA',
    geo: 'Global (NYU/LSE/HEC)',
    priority: 'HIGH',
    waiver: 'Amber',
    waiverNote: 'Waiver letter required. Strong CFA and seniority case.',
    tuitionLocal: 208080, ccy: 'USD', tuitionUsd: 208080,
    totalUsd: 223330,
    duration: '18 months',
    start: 'Sep 2027',
    deadline: '2026-09-30',
    deadlineNote: 'Confirm R1 date with admissions',
    estimated: true,
    scholarship: 'Contact financial aid. Diversity awards available.',
    scholarshipTiming: 'Contact financial aid',
  },
  {
    id: 'iese-gemba',
    name: 'IESE Global EMBA',
    geo: 'Europe',
    priority: 'HIGH',
    waiver: 'Amber',
    waiverNote: 'Waiver letter required. Strong CFA and seniority case.',
    tuitionLocal: 138000, ccy: 'EUR', tuitionUsd: 149040,
    totalUsd: 176180,
    duration: '17–18 months',
    start: 'Feb 2027',
    deadline: '2026-10-15',
    deadlineNote: 'Confirm R1 date',
    estimated: true,
    scholarship: 'Dedicated Financial Aid Office.',
    scholarshipTiming: 'Post-admission',
  },
  {
    id: 'booth-emba',
    name: 'Chicago Booth EMBA (London)',
    geo: 'US/Global',
    priority: 'HIGH',
    waiver: 'Green',
    waiverNote: 'No GMAT/GRE required.',
    tuitionLocal: 182500, ccy: 'USD', tuitionUsd: 182500,
    totalUsd: 187500,
    duration: '21–22 months',
    start: 'Sep 2027',
    deadline: '2026-10-15',
    deadlineNote: 'Confirm R1 date',
    estimated: true,
    scholarship: 'Limited information. Contact financial aid office.',
    scholarshipTiming: 'Contact financial aid',
  },
  {
    id: 'cambridge-global',
    name: 'Cambridge Global EMBA',
    geo: 'Europe',
    priority: 'HIGH',
    waiver: 'Amber',
    waiverNote: 'Post-interview waiver. 2:1 degree satisfies academic requirement.',
    tuitionLocal: 107400, ccy: 'GBP', tuitionUsd: 136398,
    totalUsd: 145479,
    duration: '20 months',
    start: 'Jan 2027',
    deadline: '2026-10-31',
    deadlineNote: 'Confirm R1 date',
    estimated: true,
    scholarship: 'Up to 50% of fees. Apply simultaneously with programme application.',
    scholarshipTiming: 'Simultaneously with application',
  },
  {
    id: 'wharton-emba',
    name: 'Wharton EMBA',
    geo: 'US/Global',
    priority: 'AMBER',
    waiver: 'Red',
    waiverNote: 'GMAT, GRE or EA mandatory. Sit the Executive Assessment.',
    tuitionLocal: 243000, ccy: 'USD', tuitionUsd: 243000,
    totalUsd: 253000,
    duration: '24 months',
    start: '~May 2027',
    deadline: '2026-11-30',
    deadlineNote: 'Confirm 2027 dates',
    estimated: true,
    scholarship: 'Merit-based. Contact Wharton financial aid.',
    scholarshipTiming: 'Contact financial aid',
  },
  {
    id: 'columbia-lbs',
    name: 'Columbia/LBS EMBA-Global',
    geo: 'US/Global',
    priority: 'AMBER',
    waiver: 'Amber',
    waiverNote: 'Waiver letter required. Strong CFA and seniority case.',
    tuitionLocal: 238800, ccy: 'USD', tuitionUsd: 238800,
    totalUsd: 249050,
    duration: '20 months',
    start: 'May 2027',
    deadline: '2026-11-30',
    deadlineNote: 'Confirm 2027 dates',
    estimated: true,
    scholarship: 'Merit scholarships available. Contact CBS/LBS financial aid.',
    scholarshipTiming: 'Contact financial aid',
  },
  {
    id: 'kellogg-emba',
    name: 'Kellogg EMBA',
    geo: 'US/Global',
    priority: 'AMBER',
    waiver: 'Green',
    waiverNote: 'No GMAT/GRE required.',
    tuitionLocal: 248472, ccy: 'USD', tuitionUsd: 248472,
    totalUsd: 253472,
    duration: '~22 months',
    start: 'Jan/Sep 2027',
    deadline: '2026-11-30',
    deadlineNote: 'Confirm 2027 dates',
    estimated: true,
    scholarship: 'Merit scholarships. Contact financial aid.',
    scholarshipTiming: 'Contact financial aid',
  },
  {
    id: 'mit-sloan',
    name: 'MIT Sloan Fellows',
    geo: 'US',
    priority: 'AMBER',
    waiver: 'Green',
    waiverNote: 'No GMAT/GRE required.',
    tuitionLocal: 161663, ccy: 'USD', tuitionUsd: 161663,
    totalUsd: 194413,
    duration: '12 months',
    start: '~Jul 2027',
    deadline: '2026-11-30',
    deadlineNote: 'Confirm 2027 dates',
    estimated: true,
    scholarship: 'Fellowship funding available. Contact admissions.',
    scholarshipTiming: 'Contact admissions',
  },
  {
    id: 'hec-paris',
    name: 'HEC Paris EMBA',
    geo: 'Europe',
    priority: 'STANDARD',
    waiver: 'Green',
    waiverNote: 'Own HEC admissions test accepted — no GMAT/GRE.',
    tuitionLocal: 110000, ccy: 'EUR', tuitionUsd: 118800,
    totalUsd: 128800,
    duration: '15–18 months',
    start: 'Multiple intakes',
    deadline: '2026-12-31',
    deadlineNote: 'Rolling',
    estimated: true,
    scholarship: 'Merit awards available. Tuition figure is the least reliable data point — verify directly.',
    scholarshipTiming: 'Contact financial aid',
    flag: 'Verify tuition directly with HEC Paris.',
  },
  {
    id: 'escp-emba',
    name: 'ESCP EMBA',
    geo: 'Europe',
    priority: 'STANDARD',
    waiver: 'Green',
    waiverNote: 'Own ESCP admissions test accepted — no GMAT/GRE.',
    tuitionLocal: 93000, ccy: 'EUR', tuitionUsd: 100440,
    totalUsd: 108791,
    duration: '18–34 months',
    start: 'Jan 2027 / Sep 2027',
    deadline: '2026-12-31',
    deadlineNote: 'Rolling',
    estimated: true,
    scholarship: 'Merit awards available. Contact ESCP financial aid.',
    scholarshipTiming: 'Contact financial aid',
  },
  {
    id: 'sda-bocconi',
    name: 'SDA Bocconi EMBA',
    geo: 'Europe',
    priority: 'STANDARD',
    waiver: 'Green',
    waiverNote: 'Own SDA Bocconi admissions test accepted — no GMAT/GRE.',
    tuitionLocal: 62000, ccy: 'EUR', tuitionUsd: 66960,
    totalUsd: 74960,
    duration: '18 months',
    start: 'Late 2027',
    deadline: '2026-12-31',
    deadlineNote: 'Rolling',
    estimated: true,
    scholarship: 'Merit scholarships available. Contact financial aid.',
    scholarshipTiming: 'Contact financial aid',
  },
  {
    id: 'imperial-emba',
    name: 'Imperial College EMBA',
    geo: 'Europe',
    priority: 'STANDARD',
    waiver: 'Green',
    waiverNote: 'No GMAT/GRE required.',
    tuitionLocal: 84500, ccy: 'GBP', tuitionUsd: 107315,
    totalUsd: 119315,
    duration: '22–23 months',
    start: 'Sep/Oct 2027',
    deadline: '2026-12-31',
    deadlineNote: 'Rolling',
    estimated: true,
    scholarship: 'African Future Leader (£20k) and Black Future Leaders (up to 50% of fees).',
    scholarshipTiming: 'Verify EMBA eligibility first',
    flag: 'Confirm whether scholarships apply to the EMBA or only the Full-Time MBA.',
  },
  {
    id: 'manchester-gemba',
    name: 'Manchester Global EMBA',
    geo: 'Europe',
    priority: 'STANDARD',
    waiver: 'Green',
    waiverNote: 'Manchester Admissions Test accepted — no GMAT/GRE.',
    tuitionLocal: 34000, ccy: 'GBP', tuitionUsd: 43180,
    totalUsd: 48180,
    duration: '2 years',
    start: 'Jan/Jul 2027',
    deadline: '2026-12-31',
    deadlineNote: 'Rolling',
    estimated: true,
    scholarship: 'Partial scholarships available. Contact financial aid.',
    scholarshipTiming: 'Contact financial aid',
  },
];

const STEPS = [
  {
    id: 'step1', num: '1', name: 'School shortlisting',
    detail: '18 schools selected. Esade removed at your request.',
    tasks: [{ ...t('s1a', 'Finalise shortlist', null), done: true }],
  },
  {
    id: 'step2', num: '2', name: 'GMAT/GRE waiver strategy',
    detail: 'All 18 schools categorised Green/Amber/Red. Wharton requires the Executive Assessment.',
    tasks: [{ ...t('s2a', 'Produce waiver strategy per school', null), done: true }],
  },
  {
    id: 'step3', num: '3', name: 'Funding and scholarship research',
    detail: '13 funding sources mapped across loans, school awards and external bodies.',
    tasks: [{ ...t('s3a', 'Complete funding research', null), done: true }],
  },
  {
    id: 'step4', num: '4', name: 'CV tailoring',
    detail: 'CV rewritten for EMBA admissions. Four items still outstanding before it is submission-ready.',
    tasks: [
      { ...t('s4a', 'Rewrite CV for EMBA admissions', null), done: true },
      t('s4b', 'Add LinkedIn URL', '2026-08-01'),
      t('s4c', 'Add board memberships and advisory roles', '2026-08-01'),
      t('s4d', 'Add professional association memberships', '2026-08-01'),
      t('s4e', 'Add team size at MBO Capital', '2026-08-01'),
    ],
  },
  {
    id: 'step5a', num: '5a', name: 'Master personal statement',
    detail: 'Six-section master statement plus adaptation guide for all 18 schools.',
    tasks: [{ ...t('s5aa', 'Write master personal statement', null), done: true }],
  },
  {
    id: 'step5b', num: '5b', name: 'Financial comparison workbook',
    detail: 'Five-sheet Excel workbook: costs, ranking, deadlines, FX, funding sources.',
    tasks: [
      { ...t('s5ba', 'Build Excel workbook', null), done: true },
      t('s5bb', 'Verify HEC Paris tuition directly', '2026-08-15'),
    ],
  },
  {
    id: 'step5c', num: '5c', name: 'School-specific paragraphs',
    detail: '100–150 words per school referencing faculty, clubs, alumni or curriculum.',
    tasks: [t('s5ca', 'Write paragraphs for all 18 schools', '2026-08-31')],
  },
  {
    id: 'step5d', num: '5d', name: 'School-specific essays',
    detail: 'Adapt the master statement to each prompt and word limit.',
    tasks: [t('s5da', 'Adapt essays per school prompt', '2026-09-10')],
  },
  {
    id: 'step6', num: '6', name: 'Interview preparation',
    detail: 'Common EMBA questions, school-specific formats, mock Q&A.',
    tasks: [t('s6a', 'Prepare interview material', '2026-10-31')],
  },
];

const ACTIONS = [
  t('a1', 'Apply to Cambridge Judge EMBA (Sep 2027 start)', '2026-11-15'),
  t('a2', 'Request recommenders — allow 6+ weeks', '2026-08-01'),
  t('a3', 'Register for the Executive Assessment (Wharton)', '2026-08-15'),
  t('a4', 'Add LinkedIn URL, board roles and memberships to CV', '2026-08-01'),
  t('a5', 'Verify HEC Paris tuition directly', '2026-08-15'),
  t('a6', 'Contact LBS, Oxford and TRIUM to confirm 2027 round deadlines', '2026-08-10'),
  t('a7', 'Contact Imperial re EMBA scholarship eligibility', '2026-08-10'),
  t('a8', 'Apply to Prodigy Finance and Lendwise on first offer', null),
];

const FUNDING = [
  { name: 'Prodigy Finance', type: 'Loan', detail: 'No collateral or co-signer. Covers Nigeria. No repayments while studying.', action: 'Apply on first offer letter' },
  { name: 'Lendwise', type: 'Loan', detail: 'UK-regulated, FCA. Fixed rates.', action: 'Apply on first offer letter' },
  { name: "Oxford Director's Awards", type: 'Scholarship', detail: 'Up to 30% of fees.', action: 'Apply at point of application' },
  { name: 'Cambridge Scholarships', type: 'Scholarship', detail: 'Up to 50% of fees.', action: 'Apply with programme application' },
  { name: 'INSEAD Diversity / Financial Fellowship', type: 'Scholarship', detail: '~60% of class receive awards.', action: 'Apply post-admission' },
  { name: 'Imperial African Future Leader', type: 'Scholarship', detail: '£20,000 award.', action: 'Confirm EMBA eligibility' },
  { name: 'Imperial Black Future Leaders', type: 'Scholarship', detail: 'Up to 50% of fees.', action: 'Confirm EMBA eligibility' },
  { name: 'LBS Merit Scholarships', type: 'Scholarship', detail: 'For self-sponsored applicants.', action: 'Apply post-offer' },
  { name: 'IESE Financial Aid', type: 'Scholarship', detail: 'Dedicated Financial Aid Office.', action: 'Apply post-admission' },
  { name: 'Tony Elumelu Foundation', type: 'External', detail: 'Pan-African leadership focus.', action: 'Research current cycle' },
  { name: 'AfDB Fellowships', type: 'External', detail: 'Supports African professionals.', action: 'Contact AfDB directly' },
  { name: 'Chevening Scholarships', type: 'External', detail: 'UK Government. UK schools only.', action: 'Confirm EMBA eligibility' },
  { name: 'Commonwealth Scholarship', type: 'External', detail: 'Nigerian citizens eligible.', action: 'Confirm EMBA eligibility' },
];

function buildSeed() {
  return {
    seedVersion: SEED_VERSION,
    createdAt: new Date().toISOString(),
    updatedAt: Date.now(),
    schools: SCHOOLS.map((s) => ({ ...s, notes: '', tasks: schoolTasks(s.deadline) })),
    steps: STEPS.map((s) => ({ ...s, tasks: s.tasks.map((x) => ({ ...x })) })),
    actions: ACTIONS.map((a) => ({ ...a })),
    funding: FUNDING.map((f) => ({ ...f })),
  };
}
